-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 16:05:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema bookshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookshare` DEFAULT CHARACTER SET utf8mb4 ;
USE `bookproject` ;

-- -----------------------------------------------------
-- Table `bookshare`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bookshare`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`books` (
  `idbook` INT NOT NULL AUTO_INCREMENT,
  `book_cover` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NULL,
  `writer` VARCHAR(45) NULL,
  `synopsis` VARCHAR(300) NULL,
  `ISBN` BIGINT NULL,
  `vacant` VARCHAR(50) NULL DEFAULT NULL,
  `occupied` VARCHAR(50) NULL DEFAULT NULL,
  `star_rating` INT NULL DEFAULT '0',
  PRIMARY KEY (`idbook`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bookshare`.`lends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`lends` (
  `idlend` INT NOT NULL AUTO_INCREMENT,
  `request_date` DATE NULL,
  `return_date` DATE NULL,
  `idreceiver` INT NULL,
  `idbook` INT NOT NULL,
  `idsender` INT NOT NULL,
  `finish` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idlend`),
  INDEX `fk_lends_users1_idx` (`idreceiver` ASC) ,
  INDEX `fk_lends_books1_idx` (`idbook` ASC) ,
  INDEX `fk_lends_users2_idx` (`idsender` ASC) ,
  CONSTRAINT `fk_lends_users1`
    FOREIGN KEY (`idreceiver`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lends_books1`
    FOREIGN KEY (`idbook`)
    REFERENCES `bookshare`.`books` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lends_users2`
    FOREIGN KEY (`idsender`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bookproject`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookproject`.`chats` (
  `idasker` INT NOT NULL,
  `idchat` VARCHAR(45) NOT NULL,
  `idlend` INT NOT NULL,
  INDEX `fk_chat_users_idx` (`idasker` ASC) ,
  PRIMARY KEY (`idchat`),
  INDEX `fk_chat_lends1_idx` (`idlend` ASC) ,
  CONSTRAINT `fk_chat_users`
    FOREIGN KEY (`idasker`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_lends1`
    FOREIGN KEY (`idlend`)
    REFERENCES `bookshare`.`lends` (`idlend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookproject`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookproject`.`messages` (
  `idchat` VARCHAR(45) NOT NULL,
  `idwriter` INT NOT NULL,
  INDEX `fk_message_chat1_idx` (`idchat` ASC),
  INDEX `fk_message_users1_idx` (`idwriter` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`idchat`)
    REFERENCES `bookproject`.`chats` (`idchat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_users1`
    FOREIGN KEY (`idwriter`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bookshare` ;

-- -----------------------------------------------------
-- Table `bookshare`.`user_has_wishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`user_has_wishes` (
  `iduser` INT NOT NULL,
  `idbook` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idbook`),
  INDEX `fk_users_has_books_books1_idx` (`idbook` ASC),
  INDEX `fk_users_has_books_users1_idx` (`iduser` ASC),
  CONSTRAINT `fk_users_has_books_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`idbook`)
    REFERENCES `bookshare`.`books` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use bookshare;