use bookshare;
INSERT INTO books (title, synopsis, writer, type, ISBN, book_cover) 
VALUES 
("Cien años de soledad", "Una saga familiar en un pueblo aislado de Colombia, llena de misterios y tragedias", "Gabriel García Márquez", "Realismo mágico", "9780307474728", "Soledad.jpg"), 
("1984", "Una distopía que reflexiona sobre el poder y la libertad individual", "George Orwell", "Ciencia ficción", "9780451524935", "1984.jpg"), 
("El señor de los anillos", "Una aventura épica en un mundo de fantasía lleno de peligros", "J.R.R. Tolkien", "Fantasía", "9780345339706","Anillos.jpg"), 
("Crónica de una muerte anunciada", "El relato de un crimen en un pequeño pueblo latinoamericano", "Gabriel García Márquez", "Realismo mágico", "9780307474728","Muerte anunciada.jpg"), 
("Harry Potter y la piedra filosofal", "Un niño descubre que es un mago y es llevado a una escuela para aprender magia", "J.K. Rowling", "Fantasía", "9788498383629","Harry Potter.jpg"), 
("Don Quijote de la Mancha", "Las aventuras de un hidalgo que se cree caballero andante", "Miguel de Cervantes", "Novela clásica", "9788416781898","Qixote.jpg"), 
("Lolita", "La obsesión de un hombre por una niña de doce años", "Vladimir Nabokov", "Ficción literaria", "9780141182537","Lolita.jpg"), 
("Las aventuras de Tom Sawyer", "Las aventuras de un niño en una pequeña ciudad a orillas del río Mississippi", "Mark Twain", "Aventuras", "9788498890798","Tom Sawyer.jpg"), 
("El gran Gatsby", "La historia de un hombre que busca recuperar un amor del pasado, en el ambiente de la alta sociedad estadounidense de los años 20", "F. Scott Fitzgerald", "Ficción literaria", "9788491050717","Gatsby.jpg"), 
("Matar a un ruiseñor", "La historia de una joven que aprende sobre la injusticia racial en Estados Unidos durante los años 30", "Harper Lee", "Ficción literaria", "9788466320728","Ruiseคor.jpg"), 
("Los juegos del hambre", "Un reality show en el que jóvenes de distintos distritos deben pelear a muerte en una arena", "Suzanne Collins", "Ciencia ficción", "9788427202122","Hambre.jpg"), 
("La ciudad y los perros", "La vida de unos jóvenes en un colegio militar en Lima, marcada por el abuso y la violencia", "Mario Vargas Llosa", "Realismo", "9788420482316","perros.jpg"), 
("Fahrenheit 451", "En un futuro distópico donde los libros están prohibidos, un bombero decide rebelarse", "Ray Bradbury", "Ciencia ficción", "9786070762910","Fahrenheit.jpg"), 
("El nombre de la rosa", "Un monje franciscano investiga una serie de asesinatos en una abadía en la Edad Media", "Umberto Eco", "Ficción histórica", "9788497592856","Rosa.jpg"), 
("La insoportable levedad del ser", "La historia de una pareja en Praga durante la invasión soviética de 1968", "Milan Kundera", "Ficción literaria", "9788420428568","Levedad.jpg"), 
("La casa de los espíritus", "La saga de una familia chilena en el siglo XX, marcada por la política y el realismo mágico", "Isabel Allende", "Realismo mágico", "9788401496119","Espiritus.jpg"), 
("Rayuela", "La obra cumbre de Julio Cortázar, en la que el lector puede elegir su propia ruta de lectura", "Julio Cortázar", "Ficción literaria", "9788466309730","Rayuela.jpg"), 
("Memorias de una geisha", "La historia de una joven vendida como esclava sexual en Japón y su camino para convertirse en geisha", "Arthur Golden", "Ficción histórica", "9788498386958","Geisha.jpg"), 
("Moby Dick", "Un obsesivo capitán de barco persigue una enorme ballena blanca", "Herman Melville", "Aventuras", "9788491052988","Moby Dick.jpg"), 
("El extranjero", "La historia de un hombre que mata a un árabe en una playa de Argelia y su posterior juicio", "Albert Camus", "Ficción literaria", "9782070360024","Extranjero.jpg"), 
("Orgullo y prejuicio", "La historia de una familia aristocrática del siglo XIX y cómo las hijas encuentran pareja", "Jane Austen", "Novela romántica", "9788420650172","Orgullo.jpg"), 
("Los cuatro vientos", "La historia de una mujer que emigra desde España a Chile en busca de una vida mejor", "Kristin Hannah", "Ficción histórica", "9788466661071","cuatrovientos.jpg"), 
("Las intermitencias de la muerte", "En un país en el que la muerte decide dejar de existir, la gente comienza a vivir eternamente", "José Saramago", "Ficción literaria", "9788490628779","Intermitencias.jpg"), 
("La vuelta al mundo en 80 días", "Un inglés apuesta que puede dar la vuelta al mundo en 80 días", "Jules Verne", "Aventuras", "9788491052032","Vueltamundo.jpg"), 
("El conde de Montecristo", "Un hombre es traicionado y encerrado en una prisión, y años después busca venganza", "Alexandre Dumas", "Novela clásica", "9788417134115","Montecristo.jpg"), 
("Drácula", "La historia del conde Drácula y su persecución por parte de un grupo de ingleses", "Bram Stoker", "Terror", "9788491053060","Dracula.jpg"), 
("El día que se perdió la cordura", "Un detective investiga la desaparición de un empresario, en un ambiente de corrupción y venganza", "Javier Castillo", "Thriller", "9788491291930","Cordura.jpg"), 
("La tregua", "La historia de un viudo que encuentra un último amor en los últimos años de su vida", "Mario Benedetti", "Ficción literaria", "9788420438185","Tregua.jpg"), 
("El príncipe de la niebla", "Tres hermanos descubren los secretos detrás de una casa antigua en la playa", "Carlos Ruiz Zafón", "Ficción histórica", "9788408205632","Niebla zafon.jpg"), 
("La hoguera de las vanidades", "La historia de un magnate de Wall Street cuya vida se hunde cuando es acusado de un delito que no cometió", "Tom Wolfe", "Ficción literaria", "9788420467283","Vanidades.jpg"),
("El perfume", "Un hombre busca crear el perfume perfecto, pero se obsesiona con el olor de las mujeres jóvenes", "Patrick Süskind", "Ficción literaria", "9788432215999","Perfume.jpg"),
("El evangelio según Jesucristo", "Una versión libre de la vida de Jesucristo, con interpretaciones polémicas sobre algunos hechos y personajes", "José Saramago", "Ficción histórica", "9788490628724","Jesucristo.jpg"),
("El cementerio de Praga", "Un falsificador crea documentos falsos que exculpan a la Iglesia católica de algunos de los crímenes que cometió en el siglo XIX", "Umberto Eco", "Ficción histórica", "9786073105517","Praga.jpg"),
("La sombra del viento", "Un joven descubre un libro misterioso de un autor desconocido, y al investigar su vida descubre un oscuro secreto", "Carlos Ruiz Zafón", "Ficción histórica", "9788408163381","Viento.jpg"),
("El código Da Vinci", "Un profesor de simbología y una criptógrafa investigan el asesinato de un curador del Louvre, y descubren una conspiración", "Dan Brown", "Ficción histórica", "9788498674024","Da Vinci.jpg"),
("Los pilares de la Tierra", "La construcción de una catedral en la Inglaterra del siglo XII, marcada por la política y la religión", "Ken Follett", "Ficción histórica", "9788497592207","Pilares.jpg"),
("La catedral del mar", "La construcción de una catedral en la Barcelona medieval, marcada por la pobreza y las luchas de poder", "Ildefonso Falcones", "Ficción histórica", "9788466345905","catedral.jpg"),
("El vuelo del cisne", "Un detective en busca de la verdad detrás de la muerte de una joven en Madrid", "José Carlos Llop", "Thriller", "9788490708054","Cisne.jpg"),
("La uruguaya", "Un hombre viaja a Montevideo en busca de su dinero, y descubre una ciudad con sus propias reglas", "Pedro Mairal", "Ficción literaria", "9788439733940","Uruguaya.jpg"),
("El jilguero", "Un joven sobrevive a un atentado en un museo y roba un cuadro famoso", "Donna Tartt", "Ficción literaria", "9788490622852","Jilguero.jpg"),
("El guardián entre el centeno", "La historia de un adolescente que huye de un internado en busca de sí mismo", "J.D. Salinger", "Ficción literaria", "9788420674208","Centeno.jpg"),
("La casa alemana", "La historia de una familia chilena y su lucha contra la dictadura de Pinochet", "Annette Hess", "Ficción histórica", "9788466349163","Alemana.jpg"),
("La librería", "La historia de una mujer que abre una librería en un pueblo conservador de Inglaterra y debe luchar contra la adversidad", "Penelope Fitzgerald", "Ficción literaria", "9788497939573","Libreria.jpg"),
("La clave está en Rebeca", "Un espía nazi se infiltra en el bando aliado durante la Segunda Guerra Mundial", "Ken Follett", "Ficción histórica", "9788466343918","Rebeca.jpg"),
("La chica del tren", "Una mujer obsesionada con un matrimonio aparentemente perfecto se ve involucrada en la desaparición de la mujer", "Paula Hawkins", "Thriller", "9788420484228","Tren.jpg"),
("El círculo", "Una joven es contratada por una empresa de tecnología en Silicon Valley, pero pronto descubre que hay un precio muy alto por la privacidad", "Dave Eggers", "Ciencia ficción", "9788408163381","Circulo.jpg"),
("El lobo estepario", "La historia de un hombre solitario que se enfrenta a su humanidad y su animalidad en un mundo que no comprende", "Hermann Hesse", "Ficción literaria", "9788435018670","Lobo.jpg"),
("La conjura de los necios", "La historia de un hombre obsesionado con demostrar la estupidez del mundo que lo rodea", "John Kennedy Toole", "Ficción literaria", "9788433966905","Conjura.jpg"),
("El retrato de Dorian Gray", "Un hombre pacta con el diablo para mantener su belleza eterna, a costa de su alma", "Oscar Wilde", "Ficción literaria", "9788467038092","Dorian.jpg"),
("La naranja mecánica", "Un joven delincuente es condenado a un tratamiento experimental para corregir su conducta violenta", "Anthony Burgess", "Ciencia ficción", "9788445071804","Naranja.jpg"),
("Frankenstein", "El clásico de Mary Shelley sobre un científico que crea a un ser a partir de la muerte", "Mary Shelley", "Terror", "9788491052506","Frankenstein.jpg");

INSERT INTO users (username) VALUES
('Juan'),
('María'),
('Manuel'),
('Ana'),
('Carlos'),
('Sofía');
