-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 18:27:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookshare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookshare` ;

-- -----------------------------------------------------
-- Schema bookshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookshare` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `bookshare` ;

-- -----------------------------------------------------
-- Table `bookshare`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`books` (
  `idbook` INT NOT NULL AUTO_INCREMENT,
  `book_cover` VARCHAR(45) NULL,
  `title` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `writer` VARCHAR(45) NOT NULL,
  `synopsis` VARCHAR(300) NOT NULL,
  `ISBN` BIGINT(20) NOT NULL,
  `vacant` VARCHAR(50) NULL,
  `occupied` VARCHAR(50) NULL,
  `star_rating` INT NULL DEFAULT 0,
  PRIMARY KEY (`idbook`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `bookshare`.`lends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`lends` (
  `idlend` INT NOT NULL AUTO_INCREMENT,
  `request_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  PRIMARY KEY (`idlend`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `bookshare`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `createbook` VARCHAR(45) NULL,
  `wishlist` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `bookshare`.`users_has_lends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`users_has_lends` (
  `iduser` INT NOT NULL,
  `idlend` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idlend`),
  INDEX `fk_usuarios_has_prestamos_prestamos1_idx` (`idlend` ASC),
  INDEX `fk_usuarios_has_prestamos_usuarios1_idx` (`iduser` ASC),
  CONSTRAINT `fk_usuarios_has_prestamos_usuarios1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bookshare`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_prestamos_prestamos1`
    FOREIGN KEY (`idlend`)
    REFERENCES `bookshare`.`lends` (`idlend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `bookshare`.`search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`search` (
  `idsearch` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `writer` VARCHAR(45) NOT NULL,
  `stars` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idsearch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshare`.`search_has_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`search_has_books` (
  `idsearch` INT NOT NULL,
  `idbook` INT NOT NULL,
  PRIMARY KEY (`idsearch`, `idbook`),
  INDEX `fk_buscar_has_libros_libros1_idx` (`idbook` ASC),
  INDEX `fk_buscar_has_libros_buscar1_idx` (`idsearch` ASC),
  CONSTRAINT `fk_buscar_has_libros_buscar1`
    FOREIGN KEY (`idsearch`)
    REFERENCES `bookshare`.`search` (`idsearch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buscar_has_libros_libros1`
    FOREIGN KEY (`idbook`)
    REFERENCES `bookshare`.`books` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshare`.`books_has_lends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshare`.`books_has_lends` (
  `idbook` INT NOT NULL,
  `idlend` INT NOT NULL,
  PRIMARY KEY (`idbook`, `idlend`),
  INDEX `fk_libros_has_prestamos_prestamos1_idx` (`idlend` ASC),
  INDEX `fk_libros_has_prestamos_libros1_idx` (`idbook` ASC),
  CONSTRAINT `fk_libros_has_prestamos_libros1`
    FOREIGN KEY (`idbook`)
    REFERENCES `bookshare`.`books` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_prestamos_prestamos1`
    FOREIGN KEY (`idlend`)
    REFERENCES `bookshare`.`lends` (`idlend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
